### ISSUE TITLE
not able to --list or anyting after upgrade. this used to work before

### ISSUE THREAD

**Issue by ashishbarmase** [skymill/automated-ebs-snapshots#18]
i think since i upgraded this not working. getting below error. credentials are correct and even created new and saved in the file. supplying correct file at command prompt.

    root@ip-10-10-11-122:~# automated-ebs-snapshots --config ~/auto-ebs-snap.conf --list
    2015-04-16 16:11:27,154 - auto-ebs - INFO - Connecting to AWS EC2 in ap-southeast-1
    2015-04-16 16:11:27,367 - auto-ebs - ERROR - 401 Unauthorized
    2015-04-16 16:11:27,367 - auto-ebs - ERROR - <?xml version="1.0" encoding="UTF-8"?>
    <Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>ea47fc83-c2a0-44fa-a88d-5ce1ea35d81e</RequestID></Response>
    Traceback (most recent call last):
      File "/usr/local/bin/automated-ebs-snapshots", line 29, in <module>
        automated_ebs_snapshots.main()
      File "/usr/local/lib/python2.7/dist-packages/automated_ebs_snapshots/__init__.py", line 168, in main
        volume_manager.list(connection)
      File "/usr/local/lib/python2.7/dist-packages/automated_ebs_snapshots/volume_manager.py", line 31, in list
        volumes = get_watched_volumes(connection)
      File "/usr/local/lib/python2.7/dist-packages/automated_ebs_snapshots/volume_manager.py", line 21, in get_watched_volumes
        filters={'tag-key': 'AutomatedEBSSnapshots'})
      File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2148, in get_all_volumes
        [('item', Volume)], verb='POST')
      File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
        raise self.ResponseError(response.status, response.reason, body)
    boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
    <?xml version="1.0" encoding="UTF-8"?>
    <Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>ea47fc83-c2a0-44fa-a88d-5ce1ea35d81e</RequestID></Response>

**Comment by sebdah** [comment]
What is it you have upgraded (from which version)? I tried this with version 0.4.0 now and it looks correct to me.

**Comment by gentitope** [comment]
How can i change the retention period? i want to do this instead of entering the volume all over again.

**Comment by sebdah** [comment]
@gentitope, remove and add the volume again. Just adding it might work, I'm not sure and can't test now.

**Comment by gentitope** [comment]
ok, Thanks. Actually the are too many to start adding all over again. Can i add the volume in bulk?
