### ISSUE TITLE
Error with forcerun on 0.6.0

### ISSUE THREAD

**Issue by mans0954** [skymill/automated-ebs-snapshots#39]
Hello,we've been using automated-ebs-snapshots successfully for some time. Tried the new 0.6.0 version out this morning with the usual arguments and get the following error:

```
automated-ebs-snapshots --access-key-id=**** --secret-access-key=**** --region=us-east-1 --run
2020-03-30 13:08:52,608 - auto-ebs - INFO - Connecting to AWS EC2 in us-east-1
2020-03-30 13:08:53,005 - auto-ebs - INFO - The newest snapshot for vol-**** is 4330 seconds old
2020-03-30 13:08:53,005 - auto-ebs - INFO - No need for a new snapshot of vol-****
2020-03-30 13:08:53,052 - auto-ebs - INFO - No old snapshots to remove
Traceback (most recent call last):
  File "/usr/local/bin/automated-ebs-snapshots", line 29, in <module>
    automated_ebs_snapshots.main()
  File "/usr/local/lib/python2.7/site-packages/automated_ebs_snapshots/__init__.py", line 173, in main
    if args.forcerun:
AttributeError: 'Namespace' object has no attribute 'forcerun'
```

This seems to be an issue with argparse, but I don't know how to work around it?

Thanks,

Christopher

**Comment by mans0954** [comment]
This is with Python 2.7 by the way. Am I right in thinking that automated-ebs-snapshots doesn't support Python 3 yet?

**Comment by mans0954** [comment]
I think I see what the problem is. `forcerun` needs to be `force_run` in line 173.

**Comment by mans0954** [comment]
Closed by https://github.com/skymill/automated-ebs-snapshots/pull/40
