### ISSUE TITLE
Script breaks if snapshot is attached to an AMI

### ISSUE THREAD

**Issue by sebdah** [skymill/automated-ebs-snapshots#4]
I get the following. The reason is that the snapshot is the base for an AMI.

```
root@ip-10-120-128-46:/etc# automated-ebs-snapshots --config /etc/automated-ebs-snapshots.conf --run
2014-04-28 06:35:53,095 - auto-ebs - INFO - Connecting to AWS EC2 in eu-west-1
2014-04-28 06:35:53,966 - auto-ebs - INFO - The newest snapshot for vol-461ee444 is 88273 seconds old
2014-04-28 06:35:53,966 - auto-ebs - INFO - Creating new snapshot for vol-461ee444
2014-04-28 06:35:54,471 - auto-ebs - INFO - Created snapshot snap-a83e8d4f for volume vol-461ee444
2014-04-28 06:35:54,956 - auto-ebs - INFO - Deleting snapshot snap-913bd876
2014-04-28 06:35:55,030 - auto-ebs - ERROR - 400 Bad Request
2014-04-28 06:35:55,030 - auto-ebs - ERROR - <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidSnapshot.InUse</Code><Message>The snapshot snap-913bd876 is currently in use by ami-836f95f4</Message></Error></Errors><RequestID>6192d985-fecc-456e-b2fb-cd72fc19be25</RequestID></Response>
Traceback (most recent call last):
  File "/usr/local/bin/automated-ebs-snapshots", line 29, in <module>
    automated_ebs_snapshots.main()
  File "/usr/local/lib/python2.7/dist-packages/automated_ebs_snapshots/__init__.py", line 155, in main
    snapshot_manager.run(connection)
  File "/usr/local/lib/python2.7/dist-packages/automated_ebs_snapshots/snapshot_manager.py", line 22, in run
    _remove_old_snapshots(connection, volume)
  File "/usr/local/lib/python2.7/dist-packages/automated_ebs_snapshots/snapshot_manager.py", line 127, in _remove_old_snapshots
    snapshot.delete()
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/snapshot.py", line 94, in delete
    return self.connection.delete_snapshot(self.id, dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2454, in delete_snapshot
    return self.get_status('DeleteSnapshot', params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1196, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidSnapshot.InUse</Code><Message>The snapshot snap-913bd876 is currently in use by ami-836f95f4</Message></Error></Errors><RequestID>6192d985-fecc-456e-b2fb-cd72fc19be25</RequestID></Response>
```

**Comment by raffael-jardim** [comment]
He managed to solve the bug
